In [2]:
from gensim.summarization import summarize
print (summarize(text))# choose similarity measure, 


The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere.
This boy was another good reason for keeping the Potters away; they didn't want Dudley mixing with a child like that.
Mr. Dursley hummed as he picked out his most boring tie for work, and Mrs. Dursley gossiped away happily as she wrestled a screaming Dudley into his high chair.


In [5]:
from gensim.summarization import keywords
print (keywords(text, words=10))

mrs
sky
beefy
gray
little
dudley
good
tawny owl
large


In [43]:
# Parameter M adjacency matrix where M_i,j represents the link from 'j' to 'i', such that for all 'j'
# sum(i, M_i,j) = 1
# Parameter d damping factor (default value 0.85)
# Parameter eps quadratic error for v (default value 1.0e-8)
# Return v, a vector of ranks such that v_i is the i-th rank from [0, 1]

import numpy as np

def pagerank(M, eps=1.0e-8, d=0.85):
    N = M.shape[1]
    v = np.random.rand(N, 1)
    v = v / np.linalg.norm(v, 1)
    last_v = np.ones((N, 1), dtype=np.float32) * 100
    
    while np.linalg.norm(v - last_v, 2) > eps:
        last_v = v
        v = d * np.matmul(M, v) + (1 - d) / N
    return v

M = np.array([[0, 0, 0, 0, 1],
              [0.5, 0, 0, 0, 0],
              [0.5, 0, 0, 0, 0],
              [0, 1, 0.5, 0, 0],
              [0, 0, 0.5, 1, 0]])

M = np.array([[0,   0,   0,   0,    0 ],
              [1/3, 0,   0,   1/2, 1/2],
              [1/3, 0,   0,   1/2,  0 ],
              [1/3, 1/2, 1/2, 0,   1/2],
              [0,   1/2, 1/2, 0,    0 ]])

v = pagerank(M, 0.00001, 0.85)

In [44]:
v
#M.shape[1]

array([[0.03      ],
       [0.26473748],
       [0.17293412],
       [0.31631588],
       [0.21601252]])

In [21]:
import networkx as nx

nx_graph = nx.from_numpy_array(M)
scores = nx.pagerank(nx_graph,1)

In [24]:
scores

{0: 0.14285745447131143,
 1: 0.19047574212729215,
 2: 0.19047574212729215,
 3: 0.26190487956713726,
 4: 0.21428618170696712}

In [6]:
d=0.85
M2 = d*M
M2

array([[0.   , 0.   , 0.   , 0.   , 0.85 ],
       [0.425, 0.   , 0.   , 0.   , 0.   ],
       [0.425, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.85 , 0.425, 0.   , 0.   ],
       [0.   , 0.   , 0.425, 0.85 , 0.   ]])

In [49]:
np.ones(M.shape)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [50]:
w0, v0 =np.linalg.eig(M2 - (1-d)*np.ones(M.shape))

In [51]:
v0

array([[ 5.60849071e-01+0.j        ,  5.60849071e-01-0.j        ,
         5.37265540e-01+0.j        ,  7.69352766e-01+0.j        ,
         9.00869559e-16+0.j        ],
       [-2.30876903e-02-0.29863814j, -2.30876903e-02+0.29863814j,
        -3.13943307e-01+0.j        ,  2.57993484e-01+0.j        ,
        -4.08248290e-01+0.j        ],
       [-2.30876903e-02-0.29863814j, -2.30876903e-02+0.29863814j,
        -3.13943307e-01+0.j        ,  2.57993484e-01+0.j        ,
         8.16496581e-01+0.j        ],
       [-4.74200822e-01+0.07376171j, -4.74200822e-01-0.07376171j,
         5.50344620e-01+0.j        ,  2.77661149e-01+0.j        ,
        -4.08248290e-01+0.j        ],
       [-4.04728685e-02+0.52351456j, -4.04728685e-02-0.52351456j,
        -4.59723547e-01+0.j        ,  4.44836299e-01+0.j        ,
         3.41726570e-16+0.j        ]])